---
apiVersion: v1
kind: Service
metadata:
  name: paismart-backend
  namespace: paismart
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: paismart
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8081"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/scheme: "http"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: paismart
  ports:
    - name: http-api
      port: 8080            # Service 端口（前端 / Ingress 调用 8080）
      targetPort: 8081      # Pod 内实际端口
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 8081
      protocol: TCP
