---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: paismart-frontend-hpa
spec:
  minReplicas: 3
  maxReplicas: 8
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
