---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: paismart-backend-hpa
spec:
  minReplicas: 3
  maxReplicas: 10
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 600
