---
apiVersion: v1
kind: Service
metadata:
  name: paismart-frontend
  namespace: paismart
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paismart
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: paismart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
